name: Build and Push - AI Agent Tasks Backend
run-name: "Build: ${{ github.event.inputs.image_tag }}"

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: "gcp-wow-food-wfc-ai-dev"
      GAR_REPOSITORY: "wfc-ai-gar"
      GAR_LOCATION: "us-central1"

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/313105558650/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
          service_account: 'wfc-ai-github-sa@gcp-wow-food-wfc-ai-dev.iam.gserviceaccount.com'

      - name: Login to GCR
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build python package
        run: |
            uv build

      - name: Publish python package
        run: |
            export UV_PUBLISH_USERNAME=oauth2accesstoken
            export UV_PUBLISH_PASSWORD=${{ steps.auth.outputs.access_token }}
            uv publish --index wfcrai-agent-utils-gar