name: Build and Publish

on:
  push:
    # fire only on semver tags, e.g. 1.2.3
    tags:
      - '*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # need write to push version bump
      id-token: write

    env:
      GCP_PROJECT_ID: gcp-wow-food-wfc-ai-dev
      GAR_REPOSITORY: wfc-ai-gar
      GAR_LOCATION: us-central1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch all tags so we can commit

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version in pyproject.toml
        run: |
          sed -i "s/^version = .*/version = \"${{ env.VERSION }}\"/" pyproject.toml

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump version to ${{ env.VERSION }}"
          file_pattern: pyproject.toml
          push_options: '--force'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/313105558650/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider
          service_account: wfc-ai-github-sa@gcp-wow-food-wfc-ai-dev.iam.gserviceaccount.com

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Build python package
        run: uv build

      - name: Publish python package
        run: |
          export UV_PUBLISH_USERNAME=oauth2accesstoken
          export UV_PUBLISH_PASSWORD=${{ steps.auth.outputs.access_token }}
          uv publish --index wfcrai-agent-utils-gar